// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel firstMapGen
#pragma kernel MidMapGen
#pragma kernel FinalMapGen
#pragma kernel BiomeGen
#pragma kernel MapComparison

StructuredBuffer<float> heightMap;
RWStructuredBuffer<float> Result;

float3 chunkPosition;

float2 BaseMapPosition;
int BaseMapSize;
float BaseMapScale;
        
int WorkMapSize;
float workMapScale;
float2 workMapPosition;
float2 workMapoffset;
float workMapAmplitude;
float workMapGradientDampening;
float depth;

float GenRandomPoint(float2 pos)
{
    return frac(cos(dot(pos, float2(23.14069263277926, 2.665144142690225))) * 12345.6789);
}
float2 CubicInterpolate(float p0, float p1, float p2, float p3, float t)
{
    float a = (p3 - p2) - (p0 - p1);
    float b = (p0 - p1) - a;
    float c = p2 - p0;
    
    return float2(a * pow(t, 3) + b * pow(t, 2) + c * t + p1, (3 * a * t + 2 * b) * t + c); // x is height, y is gradient
}

float3 BiCubicInterpolate(float2 pos)   // x is height, (y,z) is gradient // bicubic interpolation needs fixing
{
    int2 basePos = int2(floor((pos - BaseMapPosition) / BaseMapScale));
    float2 percentAcross = frac((pos - BaseMapPosition) / BaseMapScale);
    

    float2 heights[4];
    for (int i = -1; i <= 2; i++)
    {
        int baseIndex = (basePos.y + i) * BaseMapSize + basePos.x;
        heights[i + 1] = CubicInterpolate(
            heightMap[baseIndex - 1],
            heightMap[baseIndex],
            heightMap[baseIndex + 1],
            heightMap[baseIndex + 2],
            percentAcross.x);
    }
    
    return float3(CubicInterpolate(heights[0].x, heights[1].x, heights[2].x, heights[3].x, percentAcross.y).xy, CubicInterpolate(heights[0].y, heights[1].y, heights[2].y, heights[3].y, percentAcross.x).x);
}

[numthreads(16,16,1)]
void firstMapGen (uint3 id : SV_DispatchThreadID)
{
    float2 pos = workMapPosition + (id.xy * workMapScale);
    
    float height = GenRandomPoint(pos + workMapoffset) * workMapAmplitude;
    if (id.y < WorkMapSize && id.x < WorkMapSize)
    {
        Result[id.y * WorkMapSize + id.x] = height;
    }
}
[numthreads(16, 16, 1)]
void MidMapGen(uint3 id : SV_DispatchThreadID)
{
    float2 pos = workMapPosition + (id.xy * workMapScale);
    
    float3 ans = BiCubicInterpolate(pos);
    float height = ans.x;
    
    float2 gradient = ans.yz;
    if (id.x < WorkMapSize && id.y < WorkMapSize)
    {
        Result[id.y * WorkMapSize + id.x] = height + (GenRandomPoint(pos + workMapoffset) * workMapAmplitude) / ((length(gradient) * workMapGradientDampening) + 1);
    }
}
[numthreads(16, 16, 1)]
void FinalMapGen(uint3 id : SV_DispatchThreadID)
{
    float2 pos = workMapPosition + (id.yx * workMapScale);
    
    float height = BiCubicInterpolate(pos).x;
   
    if (id.y < WorkMapSize && id.x < WorkMapSize)
    {
        Result[id.y * (WorkMapSize) + id.x] = height; // this is correct
    }
}
StructuredBuffer<float3> BiomeMap;
StructuredBuffer<float> TempMap;
StructuredBuffer<float> HumidityMap;
int biomeCount;
RWStructuredBuffer<int> biomeResult;
[numthreads(16,16,1)]
void BiomeGen(uint3 id : SV_DispatchThreadID)
{
    float2 pos = float2(TempMap[id.y * (WorkMapSize) + id.x], HumidityMap[id.y * (WorkMapSize) + id.x]);
    
    float minDist=100;
    int Biome = 0;
    
    for (int i = 0; i < biomeCount; i++)
    {
        float dist = length(pos - BiomeMap[i].xy);
        if (dist < minDist)
        {
            Biome = i;
            minDist = dist;
        }
    }
    
    if (id.y < WorkMapSize && id.x < WorkMapSize)
    {
        biomeResult[id.y * (WorkMapSize) + id.x] = Biome; // this is correct
    }
}
float compMapMult;
RWStructuredBuffer<float> compResult;
[numthreads(16, 16, 1)]
void MapComparison(uint3 id : SV_DispatchThreadID)
{
    float2 pos = float2(TempMap[id.y * (WorkMapSize) + id.x], HumidityMap[id.y * (WorkMapSize) + id.x]);
    
    float diff = pos.x - (((pos.y - 0.5) * compMapMult)+0.5);
    
    if (id.y < WorkMapSize && id.x < WorkMapSize)
    {
        compResult[id.y * (WorkMapSize) + id.x] = diff; // this is correct
    }
}



