// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel firstMapGen
#pragma kernel MidMapGen
#pragma kernel FinalMapGen
#pragma kernel BiomeGen
#pragma kernel MapComparison

StructuredBuffer<float> heightMap;
RWStructuredBuffer<float> Result;

float3 chunkPosition;

float2 BaseMapPosition;
int BaseMapSize;
float BaseMapScale;
        
int WorkMapSize;
float workMapScale;
float2 workMapPosition;
float2 workMapoffset;
float workMapAmplitude;
float workMapGradientDampening;
float depth;

float GenRandomPoint(float2 pos)
{
    float3 p3 = frac(float3(pos.xyx) * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return frac((p3.x + p3.y) * p3.z);
}
float2 CubicInterpolate(float p0, float p1, float p2, float p3, float t)
{
    float a = (p3 - p2) - (p0 - p1);
    float b = (p0 - p1) - a;
    float c = p2 - p0;
    
    return float2((a * t * t * t) + (b * t * t) + (c * t) + p1, // height
                 (3 * a * t * t) + (2 * b * t) + c); // Gradient
}

float2 BiCubicInterpolate(float2 pos)   // x is height, (y,z) is gradient // bicubic interpolation needs fixing
{
    int2 basePos = int2(floor((pos - BaseMapPosition) / BaseMapScale));
    float2 percentAcross = frac((pos - BaseMapPosition) / BaseMapScale);
    

    float2 heights[4];
    for (int i = -1; i <= 2; i++)
    {
        int baseIndex = (basePos.y + i) * BaseMapSize + basePos.x;
        heights[i + 1] = CubicInterpolate(
            heightMap[baseIndex - 1],
            heightMap[baseIndex],
            heightMap[baseIndex + 1],
            heightMap[baseIndex + 2],
            percentAcross.x);
    }
    float2 finalHeightAndYGradient = CubicInterpolate(heights[0].x, heights[1].x, heights[2].x, heights[3].x, percentAcross.y);
    
    float finalXGradient = CubicInterpolate(heights[0].y, heights[1].y, heights[2].y, heights[3].y, percentAcross.y).x;
    float2 gradient = float2(finalXGradient, finalHeightAndYGradient.y) * depth / (BaseMapScale);
    float slope = length(gradient);
    float slopeRatio = saturate(slope / 3);
    
    return float2(finalHeightAndYGradient.x, slopeRatio);
}

[numthreads(16,16,1)]
void firstMapGen (uint3 id : SV_DispatchThreadID)
{
    if (id.y < (uint) WorkMapSize && id.x < (uint) WorkMapSize)
    {
    float2 pos = workMapPosition + (id.xy * workMapScale);
    
    float height = GenRandomPoint(pos + workMapoffset) * workMapAmplitude;
    
        Result[id.y * WorkMapSize + id.x] = height;
    }
}
[numthreads(16, 16, 1)]
void MidMapGen(uint3 id : SV_DispatchThreadID)
{
    if (id.x < (uint) WorkMapSize && id.y < (uint) WorkMapSize)
    {
    float2 pos = workMapPosition + (id.xy * workMapScale);
    
    float2 ans = BiCubicInterpolate(pos);
    float height = ans.x;
        float gradient = saturate(pow(1 - ans.y, workMapGradientDampening));
    
    
        
        Result[id.y * WorkMapSize + id.x] = height + ((GenRandomPoint(pos + workMapoffset) * workMapAmplitude) * gradient);
    }
}
[numthreads(16, 16, 1)]
void FinalMapGen(uint3 id : SV_DispatchThreadID)
{
    if (id.y < (uint) WorkMapSize && id.x < (uint) WorkMapSize)
    {
        float2 pos = workMapPosition + (id.yx * workMapScale);
    
        float2 ans = BiCubicInterpolate(pos);
        float height = ans.x;
        float gradient = saturate(pow(1 - ans.y, workMapGradientDampening));
    
    
        
        Result[id.y * WorkMapSize + id.x] = (height * gradient);
        //(0.5f * height) + (0.5f * height * gradient);
    }
}
StructuredBuffer<float4> BiomeMap;
StructuredBuffer<float> TempMap;
StructuredBuffer<float> HumidityMap;
int biomeCount;
RWStructuredBuffer<float2> biomeResult;
[numthreads(16,16,1)]
void BiomeGen(uint3 id : SV_DispatchThreadID)
{
    if (id.y < (uint) WorkMapSize && id.x < (uint) WorkMapSize)
    {
    float2 pos = float2(TempMap[id.y * (WorkMapSize) + id.x], HumidityMap[id.y * (WorkMapSize) + id.x]);
    
    float minDist=100;
    int Biome = 0;
    float totalDist = 0;
    float pointAmount[20];
    float totalWeight = 0;
    float weightedHeight = 0;
    float maxDist = 0;
    float exponent = 0.3;
    float minBiomeBlend = 5;
    for (int i = 0; i < biomeCount; i++)
    {
        float dist = length(pos - BiomeMap[i].xy);
        if (dist > maxDist)
        {
            maxDist = dist;
        }
        if (dist < minDist)
        {
            Biome = i;
            minDist = dist;
        }
    }
    for (int j = 0; j < biomeCount; j++)
    {
        float dist = length(pos - BiomeMap[j].xy);
        
            float weight = 1.0 / max(pow(((dist + minBiomeBlend) - minDist) / ((maxDist + minBiomeBlend) - minDist), exponent) * ((maxDist + minBiomeBlend) - minDist), 
            0.0001);

        weightedHeight += weight * BiomeMap[j].w;
        totalWeight += weight;
    }

    float height = (totalWeight > 0) ? (weightedHeight / totalWeight) : 0; // Normalize height

    
        biomeResult[id.y * WorkMapSize + id.x] = float2(Biome, height);
    }

}
    float compMapMult;
RWStructuredBuffer<float> compResult;
[numthreads(16, 16, 1)]
void MapComparison(uint3 id : SV_DispatchThreadID)
{
    if (id.y < (uint) WorkMapSize && id.x < (uint) WorkMapSize)
    {
    float2 pos = float2(TempMap[id.y * (WorkMapSize) + id.x], HumidityMap[id.y * (WorkMapSize) + id.x]);
    
    float diff = pos.x - (((pos.y - 0.5) * compMapMult)+0.5);
    
    
        compResult[id.y * (WorkMapSize) + id.x] = diff; // this is correct
    }
}



